### ISSUE TITLE
calling useOneInchSwap hook results to TypeError: Cannot read properties of undefined (reading 'chain')

### ISSUE THREAD

**Issue by mafking** [MoralisWeb3/react-moralis#244]
### Checklist

- [ ] I am not disclosing a [vulnerability](https://github.com/MoralisWeb3/react-moralis/blob/main/SECURITY.md).
- [ ] I have searched through [existing issues](https://github.com/MoralisWeb3/react-moralis/issues?q=is%3Aissue) and the [Moralis Forum](https://forum.moralis.io/).
- [ ] I can reproduce the issue with the [latest react-moralis release](https://github.com/MoralisWeb3/react-moralis/releases), [latest SDK release](https://github.com/MoralisWeb3/Moralis-JS-SDK/releases), and my server is updated to the latest version.

### Issue Description
Uncaught TypeError: Cannot read properties of undefined (reading 'chain')
    at useOneInchSwap (useOneInchSwap.ts:57:1)
    at App (App.js:40:1)
    at renderWithHooks (react-dom.development.js:16175:1)
    at mountIndeterminateComponent (react-dom.development.js:20913:1)
    at beginWork (react-dom.development.js:22416:1)
    at beginWork$1 (react-dom.development.js:27381:1)
    at performUnitOfWork (react-dom.development.js:26513:1)
    at workLoopSync (react-dom.development.js:26422:1)
    at renderRootSync (react-dom.development.js:26390:1)
    at recoverFromConcurrentError (react-dom.development.js:25806:1)

### Environment

Server

- Moralis server version: `FILL_THIS_OUT`

Client

- react-moralis version: `FILL_THIS_OUT`
- Moralis SDK version: `FILL_THIS_OUT`
- Operating system: `FILL_THIS_OUT`
- Browser: `FILL_THIS_OUT`

**Comment by AhmadDecoded** [comment]
Any progress with this one? Facing same issue and damn not being able to solve for like 3 days now. Dont know whats going wrong and even on forum no one responding.

**Comment by mafking** [comment]
> Any progress with this one? Facing same issue and damn not being able to solve for like 3 days now. Dont know whats going wrong and even on forum no one responding.

No progress,No answers, I had to suspend the swapping functionalities on my Dapp
